test:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  links:
    - db
  volumes_from:
    - cache
    - reports
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.test
    MYSQL_HOST: db
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    NOSE_INCLUDE_EXE: 1
    TEST_OUTPUT_DIR: /reports

db:
  image: mysql
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

cache:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes:
    - /tmp/cache:/cache
  entrypoint: "true"

reports:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes:
    - ../../reports:/reports
  entrypoint: "true"

agent:
  build: ../../
  dockerfile: docker/agent/Dockerfile
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"

builder:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes:
    - ../release/target:/wheelhouse
  volumes_from:
    - cache
  entrypoint: "entrypoint.sh"
  command: ["pip", "wheel", "."]